# Water Phantom
if [ "${SIMULATION_TYPE,,}" = "water_phantom" ]
then
  cd $MC_SIMULATIONS/water_phantom/
  echo 'Simulating water phantom...'
#  Gate -a "[PRIMARY_COUNT, $PRIMARY_COUNT] [PHANTOM_MODULE,$PHANTOM_MODULE] [WATER_PHANTOM_THICKNESS, $WATER_PHANTOM_THICKNESS] [WATER_PHANTOM_X, $WATER_PHANTOM_X] [WATER_PHANTOM_Y, $WATER_PHANTOM_Y] [BEAM_ENERGY, $BEAM_ENERGY] [BEAM_DELTA_X, $BEAM_DELTA_X] [BEAM_DELTA_Y, $BEAM_DELTA_Y] [FILENAME, $OUTPUT_PATH/$FILENAME] [PARTICLE_TYPE, $PARTICLE_TYPE] [SEED, $SEED]" TestMain.mac 2> $OUTPUT_PATH/${FILENAME}.log
  Gate -a "[PRIMARY_COUNT, $PRIMARY_COUNT] [PHANTOM_MODULE,$PHANTOM_MODULE] [WATER_PHANTOM_THICKNESS, $WATER_PHANTOM_THICKNESS] [WATER_PHANTOM_X, $WATER_PHANTOM_X] [WATER_PHANTOM_Y, $WATER_PHANTOM_Y] [BEAM_ENERGY, $BEAM_ENERGY] [BEAM_DELTA_X, $BEAM_DELTA_X] [BEAM_DELTA_Y, $BEAM_DELTA_Y] [FILENAME, $OUTPUT_PATH/$FILENAME] [PARTICLE_TYPE, $PARTICLE_TYPE] [SEED, $SEED]" TestMain.mac &>/dev/null
#  Gate -a "[PRIMARY_COUNT, $PRIMARY_COUNT] [PHANTOM_MODULE,$PHANTOM_MODULE] [WATER_PHANTOM_THICKNESS, $WATER_PHANTOM_THICKNESS] [WATER_PHANTOM_X, $WATER_PHANTOM_X] [WATER_PHANTOM_Y, $WATER_PHANTOM_Y] [BEAM_ENERGY, $BEAM_ENERGY] [BEAM_DELTA_X, $BEAM_DELTA_X] [BEAM_DELTA_Y, $BEAM_DELTA_Y] [FILENAME, $OUTPUT_PATH/$FILENAME] [PARTICLE_TYPE, $PARTICLE_TYPE] [SEED, $SEED]" TestMain.mac &>/output/gate.log

  echo 'Gate simulation finished. Root file can be found under /output'
fi
#WATER_PHANTOM_THICKNESS=200.0
#WATER_PHANTOM_X=50.0
#WATER_PHANTOM_Y=40.0
# Default energy of the beam in MeV
#BEAM_ENERGY=230
#BEAM_DELTA_X=0.0
#BEAM_DELTA_Y=0.0
# Default beam type
#P
